version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./backend:/app
    environment:
      - DB_URL=${DB_URL}
      - WATCHPACK_POLLING=true
    ports:
      - "8000:8000"
    env_file:
      - .env

  db:
    image: pgvector/pgvector:pg17
    volumes:
      - socialsignal_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  socialsignal_data: 