version: '3.9'

services:
  frontend:
    build:
      context: ./socialsignal
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app       
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    command: npm start

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./:/SocialSignal
    environment:
      - DB_URL=${DB_URL}
      - WATCHPACK_POLLING=true
    ports:
      - "8000:8000"

  db:
    image: pgvector/pgvector:pg17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  client:
    image: nginx
    ports:
        - 80:80

volumes:
  postgres_data: 